package view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import interface_adapter.display_course_context.DisplayCourseDetailsController;
import interface_adapter.display_course_context.DisplayCourseDetailsState;
import interface_adapter.display_course_context.DisplayCourseDetailsViewModel;
import interface_adapter.search_courses.SearchCoursesViewModel;
import interface_adapter.search_courses.SearchCoursesState;
import interface_adapter.search_courses.SearchCoursesController;
import use_case.display_course_context.display_course_details_data_transfer_objects.DisplayMeetingDetails;
import use_case.display_course_context.display_course_details_data_transfer_objects.DisplayProfessorDetails;
import use_case.display_course_context.display_course_details_data_transfer_objects.DisplaySectionDetails;
import interface_adapter.add_section.AddSectionController;
import interface_adapter.remove_section.RemoveSectionController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Set;
import java.util.List; // Added import for List

public class SearchPanel extends JPanel implements PropertyChangeListener {
    private JButton filterButton;
    private JButton searchButton;
    private JTextField searchField;
    private JPanel SearchPanel; // The root panel generated by the GUI builder
    private JScrollPane resultsScrollPane;

    // The container for all result wrappers (uses BoxLayout Y_AXIS)
    private JPanel resultsContentPanel;

    // State tracking for the collapsible panel
    private String currentlyOpenCourseId = null;
    private JPanel currentDetailsPanel = null;

    private SearchCoursesController searchCoursesController;
    private SearchCoursesViewModel searchCoursesViewModel;

    private DisplayCourseDetailsController displayCoursesController;
    private DisplayCourseDetailsViewModel displayCoursesViewModel;

    private AddSectionController addSectionController;
    private RemoveSectionController removeSectionController;

    /**
     * Creates a new SearchPanel.
     */
    public SearchPanel() {
        $$$setupUI$$$();
        setupResultsContentPanel();
        resultsScrollPane.setViewportView(resultsContentPanel);
        resultsScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        setupListeners();
    }

    /**
     * Replaces the JList with a dynamically controlled JPanel inside the JScrollPane.
     */
    private void setupResultsContentPanel() {
        resultsContentPanel = new JPanel(){
            // override method to get changable width
            @Override
            public Dimension getPreferredSize() {
                Dimension pref = super.getPreferredSize();
                if (resultsScrollPane != null && resultsScrollPane.getViewport() != null) {
                    int vw = resultsScrollPane.getViewport().getWidth();
                    if (vw > 0) {
                        // Use the viewport width, keep height from super
                        return new Dimension(vw, pref.height);
                    }
                }
                return pref;
            }
        };

        resultsContentPanel.setLayout(new BoxLayout(resultsContentPanel, BoxLayout.Y_AXIS));
        resultsContentPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
    }

    private void setupListeners() {
        searchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                executeSearch();
            }
        });

        searchField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                executeSearch();
            }
        });
    }

    private void executeSearch() {
        if (searchCoursesController != null) {
            String query = searchField.getText().trim();
            if (!query.isEmpty()) {
                searchCoursesController.execute(query);
            }
        }
    }

    public void setSearchCoursesController(SearchCoursesController controller) {
        this.searchCoursesController = controller;
    }

    public void setDisplayCoursesController(DisplayCourseDetailsController controller) {
        this.displayCoursesController = controller;
    }

    public void setAddSectionController(AddSectionController controller) {
        this.addSectionController = controller;
    }

    public void setRemoveSectionController(RemoveSectionController controller) {
        this.removeSectionController = controller;
    }

    public void setSearchCoursesViewModel(SearchCoursesViewModel viewModel) {
        this.searchCoursesViewModel = viewModel;
        this.searchCoursesViewModel.addPropertyChangeListener(
                SearchCoursesViewModel.SEARCH_RESULTS_UPDATED, this);
    }

    public void setDisplayCoursesViewModel(DisplayCourseDetailsViewModel viewModel) {
        this.displayCoursesViewModel = viewModel;
        this.displayCoursesViewModel.addPropertyChangeListener(
                DisplayCourseDetailsViewModel.DISPLAY_COURSE_CONTEXT, this);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (SearchCoursesViewModel.SEARCH_RESULTS_UPDATED.equals(evt.getPropertyName())) {
            updateSearchResults();
        } else if (DisplayCourseDetailsViewModel.DISPLAY_COURSE_CONTEXT.equals(evt.getPropertyName())) {
            updateCourseDetailsPanel();
        }
    }

    private void updateSearchResults() {
        if (searchCoursesViewModel == null) return;

        SearchCoursesState state = searchCoursesViewModel.getState();
        if (state == null) return;

        resultsContentPanel.removeAll();

        currentlyOpenCourseId = null;
        currentDetailsPanel = null;

        if (state.isError()) {
            JOptionPane.showMessageDialog(
                    this,
                    state.getErrorMessage(),
                    "Search Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        } else {
            Set<String> courses = state.getMatchedCourses();
            if (courses.isEmpty()) {
                resultsContentPanel.add(new JLabel("No courses found."));
            } else {
                for (String courseId : courses) {
                    resultsContentPanel.add(createCourseResultWrapper(courseId));
                }
            }
            //resultsContentPanel.add(Box.createVerticalGlue());
        }

        resultsContentPanel.revalidate();
        resultsContentPanel.repaint();
    }

    /**
     * Creates the wrapper JPanel for a single course result.
     */
    private JPanel createCourseResultWrapper(String courseId) {
        JPanel wrapper = new JPanel();
        wrapper.setLayout(new BoxLayout(wrapper, BoxLayout.Y_AXIS));
        wrapper.setAlignmentX(Component.LEFT_ALIGNMENT);
        wrapper.setName("Wrapper-" + courseId);
        wrapper.setAlignmentY(Component.TOP_ALIGNMENT);
        // Header Panel contains the label and button
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        headerPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        JLabel label = new JLabel(courseId);
        label.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 0));
        JButton button = new JButton("▼");
        button.setMargin(new Insets(0, 0, 0, 0));

        // The button click triggers the expand/collapse logic
        button.addActionListener(e -> showCoursePopup(courseId, wrapper));

        headerPanel.add(label, BorderLayout.WEST);
        headerPanel.add(button, BorderLayout.EAST);

        wrapper.add(headerPanel);

        return wrapper;
    }

    private void showCoursePopup(String courseId, JPanel wrapper) {
        if (displayCoursesController == null) {
            System.err.println("DisplayCoursesController not set.");
            return;
        }

        // Collapse if already open
        if (courseId.equals(currentlyOpenCourseId)) {
            if (currentDetailsPanel != null) {
                wrapper.remove(currentDetailsPanel);
                currentDetailsPanel = null;
                currentlyOpenCourseId = null;
            }
            wrapper.revalidate();
            wrapper.repaint();
            resultsContentPanel.revalidate();
            resultsContentPanel.repaint();
            return;
        }

        // Collapse other panels first
        if (currentDetailsPanel != null) {
            Component oldWrapper = currentDetailsPanel.getParent();
            if (oldWrapper instanceof JPanel) {
                ((JPanel) oldWrapper).remove(currentDetailsPanel);
                oldWrapper.revalidate();
                oldWrapper.repaint();
            }
            currentDetailsPanel = null;
        }

        currentlyOpenCourseId = courseId;
        displayCoursesController.execute(courseId);
    }

    /**
     * Called when DisplayCourseDetailsViewModel updates. Inserts the details panel inline.
     */
    private void updateCourseDetailsPanel() {
        if (displayCoursesViewModel == null || currentlyOpenCourseId == null) return;

        DisplayCourseDetailsState state = displayCoursesViewModel.getState();

        if (state.isError() || !state.getCourseId().equals(currentlyOpenCourseId)) {
            return;
        }

        JPanel targetWrapper = findWrapperPanel(currentlyOpenCourseId);
        if (targetWrapper != null) {
            // Expand the details panel
            if (currentDetailsPanel != null) {
                targetWrapper.remove(currentDetailsPanel);
            }
            JPanel newDetailsPanel = buildDetailsPanel(state);
// Set preferred size for proper expansion
            newDetailsPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
            newDetailsPanel.setPreferredSize(null);
            newDetailsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
            targetWrapper.add(newDetailsPanel);
            currentDetailsPanel = newDetailsPanel;

// Re-actions
            targetWrapper.revalidate();
            targetWrapper.repaint();
            resultsContentPanel.revalidate();
            resultsContentPanel.repaint();
            resultsScrollPane.revalidate();
            resultsScrollPane.repaint();

            for (Component c : targetWrapper.getComponents()) {
                System.out.println("  -> " + c.getClass().getName());
            }

            // Full revalidation chain
            targetWrapper.revalidate();
            targetWrapper.repaint();
            resultsContentPanel.revalidate();
            resultsContentPanel.repaint();
            resultsScrollPane.revalidate();
            resultsScrollPane.repaint();

            // Scroll to the new panel after layout
            SwingUtilities.invokeLater(() -> {
                Rectangle bounds = newDetailsPanel.getBounds();
                if (!bounds.isEmpty()) {
                    resultsScrollPane.getViewport().scrollRectToVisible(bounds);
                }
            });
        } else {
            System.err.println("Could not find wrapper for course ID: " + currentlyOpenCourseId);
        }
    }

    /**
     * Helper method to locate the correct wrapper panel in the resultsContentPanel
     * based on the course ID contained in its component name.
     */
    private JPanel findWrapperPanel(String courseId) {
        for (Component comp : resultsContentPanel.getComponents()) {
            // Java 11 compliant: manual cast
            if (comp instanceof JPanel) {
                JPanel wrapper = (JPanel) comp;
                // Check the wrapper's name attribute
                if (wrapper.getName() != null && wrapper.getName().equals("Wrapper-" + courseId)) {
                    return wrapper;
                }
            }
        }
        return null;
    }

    /**
     * Helper method to construct the detailed view of the course.
     */
    private JPanel buildDetailsPanel(DisplayCourseDetailsState state) {
        // Outer panel still uses BorderLayout so you keep the padding border
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));

        // Vertical content container (everything stacked)
        JPanel content = new JPanel();
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
        content.setAlignmentX(Component.LEFT_ALIGNMENT);

        // Title - I was trying to figure out how to make the width smaller using html but it didnt work - vic
        String courseTitle = state.getCourseTitle();
        JLabel titleLabel = new JLabel(courseTitle);
        titleLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        content.add(titleLabel);

        // Description
        JTextArea descriptionArea = new JTextArea(state.getCourseDescription());
        descriptionArea.setWrapStyleWord(true);
        descriptionArea.setLineWrap(true);
        descriptionArea.setEditable(false);
        descriptionArea.setOpaque(false);
        descriptionArea.setBorder(null);
        descriptionArea.setAlignmentX(Component.LEFT_ALIGNMENT);
        descriptionArea.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
        content.add(descriptionArea);
        content.add(Box.createVerticalStrut(10));

        // Sections list (left, just under description)
        JPanel sectionsPanel = new JPanel();
        sectionsPanel.setLayout(new BoxLayout(sectionsPanel, BoxLayout.Y_AXIS));
        sectionsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);

        List<DisplaySectionDetails> sections = state.getSectionDetails();
        if (sections != null) {
            for (int i = 0; i < sections.size(); i++) {
                DisplaySectionDetails section = sections.get(i);
                DisplayProfessorDetails prof = section.getProfessorDetails();

                StringBuilder timeLocSb = new StringBuilder();
                List<DisplayMeetingDetails> mts = section.getMeetingTimes();
                for (int j = 0; j < mts.size(); j++) {
                    DisplayMeetingDetails mt = mts.get(j);
                    if (j > 0) timeLocSb.append(", ");
                    timeLocSb.append(mt.getDayOfWeek())
                            .append(" ")
                            .append(mt.getStartTime())
                            .append("-")
                            .append(mt.getEndTime())
                            .append(" in ")
                            .append(mt.getLocation());
                }
                String timeLocation = mts.isEmpty() ? "TBA" : timeLocSb.toString();

                String sectionHtml = String.format(
                        "<html><b>%s</b><br/>%s<br/>Prof: %s (Rate My Prof Rating: <font color='green'>%.1f</font> " +
                                "/ Difficulty Rating: %.1f)</html>",
                        section.getSectionName(),
                        timeLocation,
                        prof.getName(),
                        prof.getAvgRating(),
                        prof.getAvgDifficultyRating()
                );

                // Row: label + button, horizontally aligned
                JPanel row = new JPanel();
                row.setLayout(new BoxLayout(row, BoxLayout.X_AXIS));
                row.setAlignmentX(Component.LEFT_ALIGNMENT);

                JLabel infoLabel = new JLabel(sectionHtml);
                // Let label expand vertically and horizontally with the row
                infoLabel.setAlignmentX(Component.LEFT_ALIGNMENT);


                JButton toggleButton = new JButton("Add to timetable");
                final boolean[] added = {false};

                final String courseDisplayString = state.getCourseId();
                final String sectionName = section.getSectionName();

                toggleButton.addActionListener(e -> {
                    if (added[0]) {
                        // TODO: call remove section use case
                          if (removeSectionController != null) {
                            removeSectionController.removeSection(courseDisplayString, sectionName);
                        }
                        toggleButton.setText("Add to timetable");
                    } else {
                        // Call add section use case
                        if (addSectionController != null) {
                            addSectionController.addSection(courseDisplayString, sectionName);
                        }
                        toggleButton.setText("Remove from timetable");
                    }
                    added[0] = !added[0];
                });

                // Make the row use full width so glue can push the button right
                row.add(infoLabel);
                row.add(Box.createHorizontalGlue());       // takes all remaining space
                row.add(Box.createHorizontalStrut(10));
                row.add(toggleButton);

                // Ensure row stretches to parent width
                row.setAlignmentX(Component.LEFT_ALIGNMENT);

                sectionsPanel.add(row);

                // Divider line under each row
                JSeparator separator = new JSeparator(SwingConstants.HORIZONTAL);
                separator.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1));
                separator.setAlignmentX(Component.LEFT_ALIGNMENT);
                sectionsPanel.add(separator);
                sectionsPanel.add(Box.createVerticalStrut(5));
            }
        }

        content.add(sectionsPanel);

        // Put the stacked content at the NORTH so it naturally hugs the top-left
        panel.add(content, BorderLayout.NORTH);
        // Make the details panel width follow the scrollpane viewport
//        resultsScrollPane.getViewport().addChangeListener(e -> {
//            int width = resultsScrollPane.getViewport().getWidth();
//            panel.setPreferredSize(new Dimension(width, panel.getPreferredSize().height));
//            panel.revalidate();
//        });

        return panel;
    }

    /**
     * Returns the root Swing panel for this view.
     */
    public JPanel getRootPanel() {
        return SearchPanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        SearchPanel = new JPanel();
        SearchPanel.setLayout(new GridLayoutManager(4, 5, new Insets(0, 0, 0, 0), -1, -1));
        SearchPanel.setFocusCycleRoot(true);
        SearchPanel.setMaximumSize(new Dimension(357, 63));
        SearchPanel.setPreferredSize(new Dimension(12, 25));
        resultsScrollPane = new JScrollPane();
        resultsScrollPane.setMaximumSize(new Dimension(-1, -1));
        resultsScrollPane.setMinimumSize(new Dimension(-1, -1));
        resultsScrollPane.setOpaque(true);
        resultsScrollPane.setPreferredSize(new Dimension(-1, -1));
        SearchPanel.add(resultsScrollPane, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        filterButton = new JButton();
        filterButton.setMaximumSize(new Dimension(65, 34));
        filterButton.setMinimumSize(new Dimension(50, 34));
        filterButton.setPreferredSize(new Dimension(50, 34));
        filterButton.setText("Filter");
        SearchPanel.add(filterButton, new GridConstraints(1, 2, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 34), new Dimension(80, 34), 0, false));
        searchButton = new JButton();
        searchButton.setMaximumSize(new Dimension(65, 34));
        searchButton.setMinimumSize(new Dimension(50, 34));
        searchButton.setPreferredSize(new Dimension(50, 34));
        searchButton.setText("Search");
        SearchPanel.add(searchButton, new GridConstraints(1, 3, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 34), new Dimension(80, 34), 0, false));
        searchField = new JTextField();
        searchField.setMargin(new Insets(2, 9, 2, 6));
        searchField.setMaximumSize(new Dimension(100, 34));
        searchField.setMinimumSize(new Dimension(80, 34));
        searchField.setPreferredSize(new Dimension(80, 34));
        SearchPanel.add(searchField, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(177, 34), new Dimension(185, 34), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText(" ");
        SearchPanel.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("");
        SearchPanel.add(label2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("");
        SearchPanel.add(label3, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return SearchPanel;
    }

}