package use_case.autogen;


import entity.Section;
import java.util.Set;

public class PotentialTimetable {
   boolean success;
   Set<Section> timetable;

    /**
     *
     * @param success If the DFS result of this timetable has been succesful or not
     * @param timetable The timetable generated by this search
     */

   public PotentialTimetable(boolean success, Set<Section> timetable) {
        this.success = success;
        this.timetable = timetable;
   }

}
