package entity;


import java.util.Set;

public class  PotentialTimetable {
    private final boolean success;
    private final Set<Section> sections;
    /**
     *@param success If the DFS result of this timetable has been succesful or not
     *@param sections The timetable generated by this search
     * */
    public PotentialTimetable(boolean success, Set<Section> sections) {
        this.success = success;
        this.sections = sections;
    }

    public boolean getSuccess() {
        return success;
    }

    public Set<Section> getSections() {
       return sections;
   }

    public Timetable getTimetable(){
       return new Timetable(sections);
    }
}